 export const  IMAGE = {
    hat : require('../Image/hat.png'),
    briefcase : require('../Image/briefcase.png'),
    trash : require('../Image/trash.png'),
    padlock : require('../Image/padlock.png'),
    A: require('../Image/A.jpg'),
    One: require('../Image/1.png'),
    hatwhite : require('../Image/hatwhite.png'),
    briefcasewhite : require('../Image/briefcasewhite.png'),
    trashwhite : require('../Image/trashwhite.png'),
    padlockwhite : require('../Image/padlockwhite.png'),
    london: require('../Image/london.jpeg'),
    menu: require('../Image/menu.png'),
    404: require('../Image/404.png'),
    phone: require('../Image/phone.png'),
    open: require('../Image/open.png'),
    facebook: require('../Image/facebook.png'),
    instagram: require('../Image/instagram.png'),
    linkedin: require('../Image/linkedin.png'),
    twitter: require('../Image/twitter.png'),
    placeholder: require('../Image/placeholder.png'),
}